server:
  port: 8888

spring:
  application:
    name: config-service-final
  zipkin:
    enabled: true
    baseUrl: http://zipkin:9411
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nadiamartinmontesi/spring-cloud
          searchPaths: final

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service-final:8761/eureka/